replicaCount: 2

image:
  repository: ghcr.io/craztool/cicd-sandbox
  tag: "dd87ce1cf7f83f3d27fe86b0a268b746151f456b" # Базовый хэш, который будет обновлять GitHub Actions
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: sandbox.local
